name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:rr)

variables:
  RepoName: Ready19Policy
  FolderPath: Parameters #change it you didn't follow our suggested path
  ArtifactName: parameters

resources:
  repositories:
    - repository: main
      type: github
      name: '$(RepoName)'
      endpoint: devopsjesus # only needed if repo is GitHub

trigger: #continuous integration will be enabled for all branches and the path containing the parameter files
  branches:
    include:
      - '*'
  paths:
    include:
      - Parameters #change it you didn't follow our suggested path

stages:
- stage: build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-16.04
    workspace:
      clean: all
    
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Template Files as Azure DevOps artifact'
      inputs:
        PathtoPublish: $(FolderPath)
        ArtifactName: $(ArtifactName)